### ISSUE TITLE
Error: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

### ISSUE THREAD

**Issue by benskarunya** [chemerisuk/cordova-plugin-firebase-analytics#123] opened 2019-08-12 14:49 UTC
Hi, I am getting this error using it in ionic 3 cordova@9.0.0 Android@8.0.0. Please advise

**Comment by davidquon** [comment] 2019-08-14 22:16
I'm having the same issue building for Android.  Here is my `ionic info`.
```
$ ionic info

Ionic:

   Ionic CLI                     : 5.2.4 (/Users/DQ/.nvm/versions/node/v10.15.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.4
   @angular-devkit/build-angular : 0.802.1
   @angular-devkit/schematics    : 8.2.1
   @angular/cli                  : 8.2.1
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 10 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/DQ/Library/Android/sdk)
   NodeJS            : v10.15.0 (/Users/DQ/.nvm/versions/node/v10.15.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Sierra
   Xcode             : Xcode 9.2 Build version 9C40b
```
Here's the exact error:
```
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
```
If I remove the either plugin `phonegap-plugin-barcodescanner` or `cordova-plugin-firebase-analytics` then everything builds as expected just not together.

**Comment by davidquon** [comment] 2019-08-14 22:19
This looks like a duplicate of https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/119.

**Comment by davidquon** [comment] 2019-08-14 22:37
This seemed to help me work with Version 3 which is using Android X dependencies.
https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/119#issuecomment-521445688

**Comment by SimonBrazell** [comment] 2019-09-26 06:03
Use version `cordova-plugin-firebase-analytics@2.0.4` and the project builds with no errors on `cordova-android@8.1.0`.

**Comment by sebastianovide** [comment] 2019-10-09 08:55
same here... it breaks on 3 but it work on 2

**Comment by chemerisuk** [comment] 2019-11-05 10:23
Duplicates https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/130

**Closed by chemerisuk** 2019-11-05 10:23 UTC

**Comment by nuryagdym** [comment] 2019-12-28 13:03
Solved by installing
`$ ionic cordova plugin add cordova-plugin-androidx
$ ionic cordova plugin add cordova-plugin-androidx-adapter`

as described in this [comment](https://github.com/chemerisuk/cordova-plugin-firebase-analytics/issues/119#issuecomment-521445688)
